require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/feedback_sub_codes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FeedbackSubCode. As you add validations to FeedbackSubCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # FeedbackSubCodesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      FeedbackSubCode.create! valid_attributes
      get feedback_sub_codes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      feedback_sub_code = FeedbackSubCode.create! valid_attributes
      get feedback_sub_code_url(feedback_sub_code), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FeedbackSubCode" do
        expect {
          post feedback_sub_codes_url,
               params: { feedback_sub_code: valid_attributes }, headers: valid_headers, as: :json
        }.to change(FeedbackSubCode, :count).by(1)
      end

      it "renders a JSON response with the new feedback_sub_code" do
        post feedback_sub_codes_url,
             params: { feedback_sub_code: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FeedbackSubCode" do
        expect {
          post feedback_sub_codes_url,
               params: { feedback_sub_code: invalid_attributes }, as: :json
        }.to change(FeedbackSubCode, :count).by(0)
      end

      it "renders a JSON response with errors for the new feedback_sub_code" do
        post feedback_sub_codes_url,
             params: { feedback_sub_code: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested feedback_sub_code" do
        feedback_sub_code = FeedbackSubCode.create! valid_attributes
        patch feedback_sub_code_url(feedback_sub_code),
              params: { feedback_sub_code: new_attributes }, headers: valid_headers, as: :json
        feedback_sub_code.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the feedback_sub_code" do
        feedback_sub_code = FeedbackSubCode.create! valid_attributes
        patch feedback_sub_code_url(feedback_sub_code),
              params: { feedback_sub_code: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the feedback_sub_code" do
        feedback_sub_code = FeedbackSubCode.create! valid_attributes
        patch feedback_sub_code_url(feedback_sub_code),
              params: { feedback_sub_code: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested feedback_sub_code" do
      feedback_sub_code = FeedbackSubCode.create! valid_attributes
      expect {
        delete feedback_sub_code_url(feedback_sub_code), headers: valid_headers, as: :json
      }.to change(FeedbackSubCode, :count).by(-1)
    end
  end
end
